### ISSUE TITLE
我怎么没有找到新增商品的接口代码呢？

### ISSUE THREAD

**Issue by Mecil9** [zy7y/mall#10]
是有所遗漏吗？还是在sql文件里直接生成？

**Comment by zy7y** [comment]
属于电商前台项目，新增商品的接口属于后台管理添加哈

**Comment by zy7y** [comment]
> 是有所遗漏吗？还是在sql文件里直接生成？

翻的美多商城前台api， 新增商品属于后台功能，这里不涉及，商品数据 sql文件包含了的
